In [18]:
import pickle
import os
import data_analysis.preprocessor_end as pre_processer
import numpy as np
from shutil import copyfile

In [2]:
def out_pickle(pickle_path, pick_name, variable_name):
    with open(pickle_path + pick_name + ".pkl", "wb") as pkl:
        pickle.dump(variable_name, pkl)

def in_pickle(pickle_path, pick_name):
    with open(pickle_path + pick_name + ".pkl", "rb") as pkl:
        return pickle.load(pkl)

In [3]:
word2vec_model = in_pickle("C:/Users/Abdo/Project/pre-trained word2vec models-compiled/",
                               "word2vecModel_glove_6b_300d")
vocabulary = set(word2vec_model.wv.vocab)

C:\Users\Abdo\PycharmProjects\final_project_1\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


C:\Users\Abdo\PycharmProjects\final_project_1\venv\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [4]:
# returns the average, n dimensioned, vector embedding of every word in a given document
# it sums all the vector values of every word in the document and then divides them by their count
# if a given word is not in the vocabulary of the model, it ignores it
def average_word_vectors(words, model, vocabulary, num_features):
    feature_vector = np.zeros((num_features,),dtype="float64")
    nwords = 0.
    for word in words:
        if word in vocabulary: 
            nwords = nwords + 1.
            feature_vector = np.add(feature_vector, model[word])
    
    if nwords:
        feature_vector = np.divide(feature_vector, nwords)
        
    return feature_vector

In [3]:
# utf8: true if the file is a .txt file, false otherwise
def test_classifier_on_outside_data(classifer, directory_path, txt_file_name, utf8):
    txt_data_tokens = pre_processer.preprocess_file(directory_path, txt_file_name, utf8)
    #print(txt_data_tokens)
    text_vector_representation = average_word_vectors(txt_data_tokens, word2vec_model, vocabulary, 300)
    
    prediction = classifer.predict([text_vector_representation])
    
    return prediction

def get_metrices(t_p, t_n, f_p, f_n):
    precision = t_p / (t_p + f_p)
    accuracy = (t_p + t_n) / (t_p + f_p + f_n + t_n)
    recall = t_p / (t_p + f_n)
    
    return (precision, accuracy, recall, t_p, f_p, t_n, f_n)

# takes the prediction dict and returns its confusion matrix
def get_confusion_matrix(predictions_dict):
    t_p = 0
    f_p = 0
    t_n = 0
    f_n = 0
    for label in predictions_dict:
        for moviename_prediction in predictions_dict[label]:
            prediction = moviename_prediction[1]
            # if the label is 1
            if(label == "1"):
                # the label is 1 and we predicted 1
                if prediction == 1:
                    t_p += 1
                # the label is 1 and we predicted 0
                elif prediction == 0:
                    f_n += 1
            # if the label is 0
            elif label == "0":
                # the label is 0 and we predicted 1 
                if prediction == 1:
                    f_p += 1
                # the label is 0 and we predicted 0
                elif prediction == 0:
                    t_n += 1
    return t_p, t_n, f_p, f_n

In [6]:
clf = in_pickle("C:/Users/Abdo/Project/pickle_files/","svm_final_classifier")

In [18]:
# key : label
# value [ (movie_name, prediction),...  ]
predictions_dict = { "0":[], "1":[], "not_labeled":[]}

In [19]:
direcotry_path = "C:/Users/Abdo/Project/test_data/books_txt/"
direcotry_folders = os.listdir(direcotry_path)

In [45]:
try:
    prediction = test_classifier_on_outside_data(clf,
                            direcotry_path,
                            direcotry_folders[10],False)

except:
 prediction = test_classifier_on_outside_data(clf,
                            direcotry_path,
                            direcotry_folders[10],True)

print(prediction)

AB-5475 Family Peepers by David Crane.txt


[1]


In [20]:
for folder in direcotry_folders:
    movies = os.listdir(direcotry_path + folder + "/")
    for movie_name in movies:
        try:
            movie_prediction = test_classifier_on_outside_data(clf, direcotry_path + folder + "/", movie_name, False)
        except:
            print("\n")
            movie_prediction = test_classifier_on_outside_data(clf, direcotry_path + folder + "/", movie_name, True)
            print("\n")

        predictions_dict[folder].append( (movie_name, movie_prediction) )

5042 Voodoo In Haiti by Aubrey Wilder.txt


A Night To Remember by Argus.txt


AB-1609 House of Dark Pleasure by Gloria Day.txt


AB-1676 Beasts Are Better by Richard Long.txt


AB-1680 The Dog Ballers by Don Russell.txt


AB-5247 Incest Wifeby M J Jacobs.txt


AB-5341 Mother With The Hots by Kathy Andrews.txt


AB-5353 Harder! Mom Said by Kathy Andrews.txt


AB-5356 What A Sucking Mother! by Kathy Andrews.txt


AB-5389 Daddy's Naughty Daughters by Bob Wallace.txt


AB-5475 Family Peepers by David Crane.txt


AB-5480 Billy's Hot Mom by Kathy Andrews.txt


AB-5491 Three Sucking Daughters by Dan Reagan.txt


AB-5548 A Wild Family Party by Hank Borden.txt


AB-5557 Pay For Play Cheerleaders by Victoria Parker.txt


AB-5574 Twin Farmgirl Cousins by Ron Taylor.txt


AB-5592 First Time In The Behind by Ron Taylor.txt


AB-5602 When Mom And Dad Are Away by Author Unknown.txt


AB-5617 Brothers Ball Best by Ray Mills.txt


AB-5618 Incest Schoolgirls by Victoria Parker.txt


ACDC-182 Swap Night.txt


All_in_the_Family.txt


ASP-2021 Driven Into Swapping.txt


AudioBook The Gunslinger Chapter - English (auto-generated).txt


AW-103.TXT


A_Mother-Daughter_Twosome.txt


A_Wild_Family_Party.txt


BB-6565 Deep Crotch Mother.txt


BB-6565 Deep Crotch Mother.txt




BDB-1023 Step-Daughter Initiation.txt


Beast Humping by Ron Bywood.txt


Billy's_Hot_Mom.txt


BL-5341 Emily_s Lips By Arthur Alexander.txt


Blackmailed.txt


Brothers_Ball_Best.txt


Carve the Mark Chapter 1 - English (auto-generated).txt


Carve The Mark Chapter 2 - English (auto-generated) (1).txt
Carve The Mark Chapter 2 - English (auto-generated).txt


Carve the Mark Chapter 4 - English (auto-generated).txt


Carve The Mark Chapter 5 - English (auto-generated).txt
CC-241 The Family Haven BOOK ONE by Author Unknown.txt


Charles_Wykes.Brothers_and_Sisters.FAM-119.TXT


Cheryl's Cumuppance - Ex-Wives III.txt


CHINA TEEN PHOTO SLAVES by Loren Ryder.txt


Daddy's_Naughty_Daughters.txt


Daughters_In_Heat.txt


Desert Slave by Argus.txt
Dog Lover's Diary by Horst Kepple.txt


Doggie Farm by John Reskin.txt


Eager_Horny_Cousin.txt


EC-1120 Bestiality and a Young Girl by Kathleen Hennessy.txt


EX-WIVES - PART IV DESTINY.txt


EX-WIVES INHERITANCE - PART 1 - JULIA DAWSON.txt


EX-WIVES INHERITANCE - PART 2 - DOMINIQUE'S TAMING.txt


FAM-119 Brothers And Sisters by Charles Wykes.txt


Family_Peepers.txt


First_Time_In_The_Behind.txt


FLP-135 Girl's Camp Counselor by Paul Sutherland.txt


GE-2033 Spouse In Torment by Jason Cannon.txt


GGE-101 Teaching Swapping by Author Unknown.txt


GK-550 The Soldier's Wife by Alex Ayers.txt


gs-59.txt


gsv-133.txt


Hard to tell by Arianne.txt


herbarkingstud.txt


Her_Husband's_Boss.txt


House_Of_Evil.txt


Impossible-Standards.txt


Impossible-Standards.txt




Incest Schoolgirls.txt


Incest_Wife.txt


In_Bondage_Schoolgirl.txt


j-3.txt


kc-126.txt


LB1348 The Family Sucks A Lot .txt


lcs-70003.txt


Legal Briefs by Argus.txt


Little Monsters by Kara Thomas, read by Phoebe Strole _ Brittany Pressley - Audiobook Excerpt - English (auto-generated).txt
LL-0229 Shack-Ups! by Fran Furnivall.txt


LL-0251 Auntie’s Naughty Boys by Hank Faber.txt


LL-0344 His Sexpot Sis by Robert G. Haill.txt


LLP0101 The Abducted Bride.txt


LLP0102 The Blackmailed Wife.txt


LLP0103 A Neighborhood Party.txt


LLP0171 Honeymoon Hotel.txt


LLP0348 The Motorcyclist_s Wife.txt


LLP0874 A Sister_s Lust by Audrey Gait.txt


LLP0874 A Sister_s Lust by Audrey Gait.txt




m-4006.txt


m-60212.txt


mastlilg.txt


mlp-146.txt


nakedwithherdog.txt


Naked_Wet_Daughter.txt


Naughty Schooling by David Shaw.txt
Naughty_Wild_Cousin.txt


nd-141.txt


ns-451.txt


oa-117.txt


OES-117 Maggie_s Moist Mouth.txt


OES-138 The Mouth Seducers by Fred Tracy.txt


oph-217.txt


ORL-149 Oral Zone by Otto Gerbert.txt


ORL-155 Oral Nieces by Jim Stacey.txt


p-2064.txt


Passionate_Sister.txt


Paul_Sutherland.Girls_Camp_Counselor.FLP-135.txt


Peeper by Argus.txt


Pirates' Sex Toys by Argus.txt
pp-11.txt


pp-13.txt


pp-7001.txt


pp-7002.txt


pp-7012.txt


pp-7027.txt


pp-7042.txt


pp-7046.txt


pp-7093.txt


pp-7205.txt


pp-7206.txt


pp-7208.txt


pp-7285.txt


pp-7304.txt


pp-7339.txt


pp-7375.txt


pp-7388.txt


pp-7397.txt


pp-7524.txt


pp-7541.txt


pp-8001.txt


pp-8016.txt


pp-8049.txt


pp-8051.txt


pp-8060.txt


Punching Bag by Argus.txt
ras-1405.txt


rcl-216.txt


RCL-228 Little Boys And Laura.txt


sb-206.txt


sc-173.txt


Schoolgirl_Bondage.txt


Seduced_Young_Wife.txt


Servile Sluts by Jay Merson.txt


Sexy Sailors by Frances La Gatta.txt


Sister's_Husband.txt


Sister's_Wet_Panties.txt


Sister_Sucks_Best.txt


Slave_Trader's_Captive.txt


Slut by Argus.txt


Summer Lovers by Argus.txt


Taken By Force by Jay Merson.txt


THE CAPTIVE by Amber Jameson.txt


THE CONTRACT by Sarah Fisher.txt


THE DRIVERS by Henry Morgan.txt


The Secret Fantasies of a Suburban Girl by Laura Jenkins.txt
The_Orgiastic_Cult.txt


The_Rancher's_Wife.txt


The_Seductive_Sister-In-Law.txt


The_Tempted_Tourist.txt


The_Unfaithful_Girlfriend.txt


The_Weekend_Captive.txt


Three-Way_Weekend.txt


Three_Sucking_Daughters.txt


Trio.txt
Tween_Sister's_Hot_Thighs.txt


Twin_Farmgirl_Cousins.txt


Wanting_Everyone.txt


What_A_Sucking_Mother.txt


When_Mom_And_Dad_Are_Away.txt


White Girls In Africa by Argus.txt


WOMEN ON THE CHAIN GANG by Jay Merson.txt


YW-118 Ecstasy-Between Young _ Old by Lorna Miller.txt


YW-119 Sex Teaching Teacher.txt


12 Dancing Princesses _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
2 Stories _ The Time Princess _ bedtime stories _ Stories _ English Story - English (auto-generated).txt
20 Best English Stories For Kids Collection _ Story Time _ Moral Stories For Kids In English - English (auto-generated).txt


9825-around-the-world-with-a-chilli-childrens-nonfiction-book.txt


9825-around-the-world-with-a-chilli-childrens-nonfiction-book.txt


A Little Mouse Who Was Princess _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Animated Kids Stories - Kids Hut Storytelling (English Stories) Traditional - English (auto-generated).txt


A_Whistling_good_idea_FKB.txt


A_Whistling_good_idea_FKB.txt


Beauty and the Beast in English _ Story _ English Fairy Tales - English (auto-generated).txt
BEDTIME STORIES AND FAIRY TALES FOR KIDS - TOP 10 NEW STORIES FOR KIDS __ KIDS STORIES - English (auto-generated).txt


Bob The Train _ Went To The Farm _ Old MacDonald Had A Farm by Bob The Train - English.txt
charly and the cocalte facotry.txt


Donkey Stories - Tia and Tofu Storytelling __ Kids Hut Stories - Moral Stories To learn For Kids - English (auto-generated).txt
Elves and The Shoe Maker _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Emperor's New Clothes _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
English Kids Stories - Tia and Tofu English Storytelling __ English Story Series - Animated Stories - English (auto-generated).txt


English Stories - Animated Stories For Kids __ Moral Stories and Bedtime Stories For Kids - English (auto-generated).txt
English Stories For Kids - Kids Hut Stories __ Animated Stories For Kids - Moral Stories - English (auto-generated).txt


faceToFaceWithTheGorillaKing.txt


faceToFaceWithTheGorillaKing.txt




Fairy Tales For Kids - Animated Fairy Tales and Bedtime Stories __ Kids Hut Stories - English (auto-generated).txt


Five Peas In Pod Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Flawless Prince in English _ Story _ English Fairy Tales - English (auto-generated).txt
Hansel And Gretel in English _ Story _ English Fairy Tales - English (auto-generated).txt
Happy Prince Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Heidi Story _ Bedtime Stories _ Stories for Kids _ Fairy Tales _ My Pingu Tv - English (auto-generated).txt


invasion-of-the-hazmats.txt


invasion-of-the-hazmats.txt




Jack and The Beanstalk Story _ Bedtime Stories _ Stories for Kids _ Fairy Tales _ My Pingu Tv - English (auto-generated).txt
jataka_tv1.txt


jataka_tv1.txt




Jorinda And Jorindel Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Kids Hut Stories - Tia and Tofu Storytelling __ Moral and Learning Stories In English For Kids - English (auto-generated).txt
KIDS STORIES - ANIMATED STORIES - English (auto-generated).txt


Kids Stories - Animated Stories For Kids __ Bedtime Stories For Kids - Moral To Learn For Kids - English (auto-generated).txt
KIDS STORIES - ANIMATED STORIES FOR KIDS __ COOL STORIES FOR KIDS - KIDS MORAL STORIES - English (auto-generated).txt
KIDS STORIES - ANIMATED STORIES FOR KIDS __ MORAL STORIES - TIA AND TOFU STORYTELLING - English (auto-generated).txt


KIDS STORIES - ANIMATED STORIES FOR KIDS __ TIA AND TOFU ANIMATED STORY SERIES - English (auto-generated).txt
KIDS STORIES - ANIMATED STORIES FOR KIDS __ TIA AND TOFU STORYTELLING - English (auto-generated).txt


KIDS STORIES - BEAUTY AND THE BEAST (Full Version) __ Storytelling By Tia and Tofu - English (auto-generated).txt
KIDS STORIES - Best Stories For Kids - English (auto-generated).txt


Kids Stories - Kids Hut Stories - English (auto-generated).txt
Kids Stories - Kids Hut Storytelling - English (auto-generated).txt
Kids STORIES - LEARNING STORIES FOR KIDS __ PETER PAN & MORE - English (auto-generated).txt


KIDS STORIES - RACE STORIES __ FABLES FOR KIDS - THE BET STORY __ STORYTELLING - English (auto-generated).txt
KIDS STORIES - STORIES FOR KIDS __ BEST STORIES FOR KIDS - KIDS HUT STORYTELLING - English (auto-generated).txt


KIDS STORIES - STORIES TO LEARN __ MORAL STORIES - HAPPY PRINCE & MORE - English (auto-generated).txt
KIDS STORIES - The Christmas Story, Christmas Carol and The Lazy Girl __ Storytelling By Tia & Tofu - English (auto-generated).txt


KIDS STORIES - The Fox and The Crab Full Stories __ Animated Stories For Kids - Tia and Tofu Stories - English (auto-generated).txt
Kids Stories - The Horse & the Snail And The Lazy Horse - Kids Hut Storytelling - English (auto-generated).txt
KIDS STORIES - The Wolf and The Seven Goats Story, The Fox & The Stork - English (auto-generated).txt
Kids Stories By Kids Hut_ Aladdin and The Beauty & The Beast __ Animated Full Movies - English (auto-generated).txt


Kids Stories _ The Lazy Girl and The Jack and The beanstalk __ Animated Stories For Kids - English (auto-generated).txt
Kids Story Collection _ Hansel and Gretel - 12 Dancing Princesses - English (auto-generated).txt
King Midas Touch Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Peppa Pig English Episodes - Halloween Party! Peppa Pig Official - English (auto-generated).txt


Peppa Pig English Episodes _ Peppa Pig about Town _ Peppa Pig Official - English (auto-generated).txt
Pied Piper Of Hamelin _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Pinocchio & More - KIDS STORIES __ Kids Hut Storytelling - Animated Stories For Kids - English (auto-generated).txt


Pinocchio Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
pisus-revenge-middle-grade-fantasy.txt


pisus-revenge-middle-grade-fantasy.txt




PJ Masks Full Episode 7 2016 New - English (auto-generated).txt
Pocahontas and More Stories For Kids - Animated Story Series For Kids __ Tia and Tofu Storytelling - English (auto-generated).txt


Princess fairy tales 2 _ Rumpelstiltskin _ Thumbelina _ Snow White _The Little Mermaid _ My Pingu Tv - English (auto-generated).txt
Princess Fairy Tales _ Cinderella _ Rapunzel _ Beauty and the Beast _ Frog Prince _ Sleeping Beauty - English (auto-generated).txt


Puss in Boots Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Rapunzel in English _ Story _ English Fairy Tales - English (auto-generated).txt
Rapunzel Story _ Bedtime Stories _ Stories for Kids _ Fairy Tales _ My Pingu Tv - English (auto-generated).txt
Rumpelstiltskin Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Sam-Dragon-FKB-PDF-180831.txt


Sam-Dragon-FKB-PDF-180831.txt




Six Animal Stories _ Bedtime Stories _ Stories for Kids _ Fairy Tales _ My Pingu Tv - English (auto-generated).txt
Snow White story & Snow White songs _ Fairy Tales and Bedtime Stories for Kids - English (auto-generated).txt
Tania-In-A-Winter-Wonderland-Kanika-G.txt


The Ant and the Grasshopper _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
The Fisherman and His Wife _ Bedtime Stories _ My Pingu Tv - English (auto-generated).txt
The Four Brahmins Story _ Bedtime Stories _ Stories for Kids _ Fairy Tales _ My Pingu Tv - English (auto-generated).txt
The Frog And The Ox Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
THE FROG PRINCE - KIDS STORY IN ENGLISH __ ANIMATED MOVIES FOR KIDS - FULL STORY - English (auto-generated).txt


The Giving Tree Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
The Golden Bird Story _ Story For Kids _ My Pingu Tv - English (auto-generated).txt
The Intelligent Buffalo _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
The Little Match Girl _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
The Little Red Riding Hood & More - Animated Stories For Kids __ Traditional Stories For Kids - English (auto-generated).txt


The Magic Pot Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
The Red Shoes Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
The Snow Queen Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
The Ugly Duckling and the Little Mermaid - HCA - The Fairytaler - English (auto-generated).txt
The Wild Swans Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt


The Wizard of Oz Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
THE WOLF AND SEVEN LITTLE GOATS - ANIMATED STORIES __ KIDS HUT STORYTELLING - TIA AND TOFU STORIES - English (auto-generated).txt
the-lion-who-wouldnt-try_english_FKB.txt


the-lion-who-wouldnt-try_english_FKB.txt


The-Little-Alien-Book-1-FKB-180317-Middle-Grade-Science-Fiction.txt


The-Little-Alien-Book-1-FKB-180317-Middle-Grade-Science-Fiction.txt




The-New-Kid-Kanika-G.txt
Three Little Pigs Story _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
Thumbelina Story _ Bedtime Stories _ Stories for Kids _ Fairy Tales _ My Pingu Tv - English (auto-generated).txt
Travelling Companion in English _ Story _ English Fairy Tales - English (auto-generated).txt
Witch and Giant Stories _ Jack and the Beanstalk _ Hansel and Gretel _ Fairy tales - My Pingu Tv - English (auto-generated).txt


Wolf And Seven Little Goats _ Stories for Kids _ My Pingu Tv - English (auto-generated).txt
11 TRUE SCARY STORIES From Reddit [MEGA COLLABORATION #3] - English (auto-generated).txt


11 TRUE SCARY STORIES From Reddit [MEGA COLLABORATION #4] - English (auto-generated).txt


14 Horror Stories Animated (Compilation of 2015) - English (auto-generated).txt


14 More Horror Stories Animated (Compilation of 2016) - English (auto-generated).txt


16 True Scary Stories [Compilation Vol.14] - English (auto-generated).txt


5 Horror Stories Animated (Compilation of Dec. 2018) - English (auto-generated).txt
A novel by - Jeffrey Carver ( PDFDrive.com ).txt


A novel by - Jeffrey Carver ( PDFDrive.com ).txt




A Sherlock Holmes Novel_ The Sign of the Four Audiobook - English (United Kingdom).txt


A TALE OF TWO CITIES by Charles Dickens - FULL AudioBook _ Greatest AudioBooks (Book 1 of 3) V2 - English (auto-generated).txt


Audiobooks - The Little Prince - Antoine de Saint-Exupéry - English (auto-generated).txt


Audiobook_ Miss Philura's Wedding Gown by Florence Morse Kingsley _ AudioBooks Classic - English (auto-generated).txt


aufg.txt


aufg.txt




CELEBRATED CRIMES_ THE MAN IN THE IRON MASK - FULL AudioBook _ GreatestAudioBooks - English (auto-generated).txt


Chapter 1 - The Boy Who Lived (Harry Potter and the Sorcerer's Stone) - English (auto-generated).txt
Crime-and-Punishment.txt


CUSTER BATTLEFIELD_ A History And Guide To The Battle Of The Little Bighorn _ Greatest AudioBooks - English (auto-generated).txt


Dead Man's Planet [SF Audiobook] - English (auto-generated).txt
Dead Men Tell No Tales audiobook (FULL Audiobook) - part (1 of 3) - English (auto-generated).txt


elif-safak-esq-kko-eng.txt


elif-safak-esq-kko-eng.txt




EMMA Audiobook by Jane Austen _ Full Audio book with Subtitles _ Part 1 of 2 - English.txt


EMMA Audiobook by Jane Austen _ Full Audio book with Subtitles _ Part 1 of 2 - English.txt




Encyclopedia of Comic Books and Graphic Novels ( PDFDrive.com ).txt


Encyclopedia of Comic Books and Graphic Novels ( PDFDrive.com ).txt




English Learning Audio Book, through picture, story English subtitle 20 - English (auto-generated).txt
Gone Girl by Gillian Flynn ( PDFDrive.com ).txt


Gone Girl by Gillian Flynn ( PDFDrive.com ).txt




Good+Morning+Holy+Spirit.txt


Good+Morning+Holy+Spirit.txt




HOLY BIBLE - Book of MARK - Word English Bible (WEB) - FULL AudioBook _ GreatestAudioBooks - English (auto-generated).txt


IMPROVE LISTENING SKILLS VIA GREAT NOVELS - The Adventures of HuckleBerry Finn [Part I] - English (auto-generated).txt


Learn English Through Story - Jane Eyre- Practice Listening English - English (auto-generated).txt


Learn English Through Story - The House On The Hill by Elizabeth Laird - English (auto-generated).txt
Learn English Through Story - The Stranger by Norman Whitney - English (auto-generated).txt


Learn English Through Story - The Woman Who Disappeared (Elementary) Audiobook with Subtitles - English (auto-generated).txt


Learn English Through Story -The Willing Ghost- Practice Listening English - English (auto-generated).txt
Learn English with Audio Story - Jane Eyre - English (auto-generated).txt


Learn English with Audio Story - The Adventures of Tom Sawyers - English (auto-generated).txt


Learn English With Story Love or Money level 1 - English (auto-generated).txt
Learn English With Story White Death subtitled level 1 - English (auto-generated).txt


Loves-Fool.txt


Loves-Fool.txt




Muhammad_ His Life Based on the Earliest Sources ( PDFDrive.com ).txt


pride-and-prejudice.txt


Rose O' The River Full Audiobook by Kate Douglas WIGGIN by General Fiction - English (auto-generated).txt


Sanctuary Full Audiobook by Edith WHARTON by General Fiction Audiobook - English (auto-generated).txt


The Comedy of Errors (Improved Reading) (FULL Audiobook) - English (auto-generated).txt


THE FALL OF THE HOUSE OF USHER by Edgar Allan Poe - FULL AudioBook _ GreatestAudioBooks V1TA - English (auto-generated).txt
The Fault in Our Stars ( PDFDrive.com ).txt




The Fault in Our Stars ( PDFDrive.com ).txt




The Gifts of Imperfection_ Embrace Who You Are ( PDFDrive.com ).txt


The Gifts of Imperfection_ Embrace Who You Are ( PDFDrive.com ).txt




THE MAN FROM SNOWY RIVER by Banjo Paterson - FULL AudioBook _ GreatestAudioBooks - English (auto-generated)(1).txt


THE MAN FROM SNOWY RIVER by Banjo Paterson - FULL AudioBook _ GreatestAudioBooks - English (auto-generated).txt


The Metamorphosis by Franz Kafka (Free Audio Book in English Language) - English.txt


The Monk Who Sold His Ferrari ( PDFDrive.com ).txt


The Secret of Dreams - FULL Audio Book - by Yacki Raizizun _ GreatestAudioBooks - English (auto-generated).txt
THE STORY OF ATLANTIS - FULL AudioBook _ Greatest Audio Books - English (auto-generated).txt


THE VAMPYRE by John William Polidori - FULL AudioBook _ Greatest AudioBooks - English (auto-generated)(1).txt


THE VAMPYRE by John William Polidori - FULL AudioBook _ Greatest AudioBooks - English (auto-generated).txt


The Watsons by Jane Austen (FULL Audio Book) - English (auto-generated).txt


The Woman Who Tried to be Good Edna Ferber audiobook Short Story - English (auto-generated).txt
The-Brothers-Karamazov.txt


the-forgotten-room-a-novel-lincoln-child.txt


the-forgotten-room-a-novel-lincoln-child.txt




the-great-gatsby.txt


The-House-of-the-Dead.txt


The-House-of-the-Dead.txt




The-Idiot.txt


The-Peasant-Marey.txt


The-Peasant-Marey.txt


To Build a Fire by Jack London a Free Audio Book - English (auto-generated).txt


[Fantasy Tale from the Author of Dracula] The Castle of the King (Bram Stoker Audiobook) - English (auto-generated).txt


In [21]:
out_pickle("C:/Users/Abdo/Project/pickle_files/","predictions_dict_books_txt", predictions_dict)

In [4]:
movies_txt_dict = in_pickle("C:/Users/Abdo/Project/pickle_files/","predictions_dict_movies_txt")
books_txt_dict = in_pickle("C:/Users/Abdo/Project/pickle_files/","predictions_dict_books_txt")

In [5]:
books_txt_dict.pop('not_labeled', None)

[('11 TRUE SCARY STORIES From Reddit [MEGA COLLABORATION #3] - English (auto-generated).txt',
  array([0])),
 ('11 TRUE SCARY STORIES From Reddit [MEGA COLLABORATION #4] - English (auto-generated).txt',
  array([1])),
 ('14 Horror Stories Animated (Compilation of 2015) - English (auto-generated).txt',
  array([1])),
 ('14 More Horror Stories Animated (Compilation of 2016) - English (auto-generated).txt',
  array([1])),
 ('16 True Scary Stories [Compilation Vol.14] - English (auto-generated).txt',
  array([1])),
 ('5 Horror Stories Animated (Compilation of Dec. 2018) - English (auto-generated).txt',
  array([1])),
 ('A novel by - Jeffrey Carver ( PDFDrive.com ).txt', array([0])),
 ('A Sherlock Holmes Novel_ The Sign of the Four Audiobook - English (United Kingdom).txt',
  array([1])),
 ('A TALE OF TWO CITIES by Charles Dickens - FULL AudioBook _ Greatest AudioBooks (Book 1 of 3) V2 - English (auto-generated).txt',
  array([1])),
 ('Audiobooks - The Little Prince - Antoine de Saint-Exupé

In [6]:
# key: movies_txt_dict, books_txt_dict
# value: (precision, accuracy, recall, t_p, f_p, t_n, f_n)
test_results_dict = { }

In [7]:
# get the confusion matrix for each one of the cases
movies_txt_confusion_matrix = get_confusion_matrix(movies_txt_dict)
books_txt_confusion_matrix = get_confusion_matrix(books_txt_dict)

In [8]:
# the movies text case
movies_txt_metrics = get_metrices(movies_txt_confusion_matrix[0],
                                  movies_txt_confusion_matrix[1],
                                  movies_txt_confusion_matrix[2],
                                  movies_txt_confusion_matrix[3])

In [9]:
# the books text case
books_txt_metrics = get_metrices(books_txt_confusion_matrix[0],
                                  books_txt_confusion_matrix[1],
                                  books_txt_confusion_matrix[2],
                                  books_txt_confusion_matrix[3])

In [10]:
test_results_dict["movies_txt_dict"] = movies_txt_metrics
test_results_dict["books_txt_dict"] = books_txt_metrics

In [29]:
out_pickle("C:/Users/Abdo/Project/pickle_files/","test_results_dict", test_results_dict)

In [8]:
test_results_dict = in_pickle("C:/Users/Abdo/Project/pickle_files/","test_results_dict")

In [11]:
print(test_results_dict["books_txt_dict"])

(0.36681222707423583, 0.4128787878787879, 0.8936170212765957, 84, 145, 25, 10)


In [12]:
books_txt_dict = in_pickle("C:/Users/Abdo/Project/pickle_files/","predictions_dict_books_txt")

In [13]:
# key: predicted label
# value: [book1_name, ..... ]
non_labeled_books_dict = {0: [], 1:[]}

In [14]:
for book_name_prediction_pair in books_txt_dict["not_labeled"]:
    book_name = book_name_prediction_pair[0]
    prediction = book_name_prediction_pair[1][0]
    
    non_labeled_books_dict[prediction].append(book_name)

In [20]:
for prediction in non_labeled_books_dict:
    for book in non_labeled_books_dict[prediction]:
        os.rename("C:/Users/Abdo/Project/test_data/books_txt/not_labeled/"+book,
                  "C:/Users/Abdo/Project/test_data/books_txt/not_labeled/"+str(prediction)+"_"+book)